In [1]:
import pandas as pd
import warnings as wr
wr.filterwarnings('ignore')

In [2]:
df = pd.read_csv('weight-height.csv')
df.head()

  Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [7]:
df.Gender = le.fit_transform(df[['Gender']])

In [9]:
df.head()

   Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [11]:
df.tail()

      Gender     Height      Weight
8550       0  60.483946  110.565497
8551       0  63.423372  129.921671
8552       0  65.584057  155.942671
8553       0  67.429971  151.678405
8554       0  60.921791  131.253738

# Go Ahead

In [22]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split as tts

In [28]:
X = df.drop('Weight', axis=1)

In [76]:
from matplotlib import pyplot as plt

In [32]:
X.head()

   Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [34]:
y = df['Weight']

In [36]:
y.head()

0    241.893563
1    162.310473
2    212.740856
3    220.042470
4    206.349801
Name: Weight, dtype: float64

In [82]:
df.corr()

          Gender    Height    Weight
Gender  1.000000  0.682524  0.790208
Height  0.682524  1.000000  0.922975
Weight  0.790208  0.922975  1.000000

In [38]:
X_train, X_test, y_train, y_test = tts(X,y, test_size = 0.3, random_state = 42)

In [40]:
len(X_train)

5988

In [42]:
len(X_test)

2567

In [48]:
reg = LinearRegression()

In [50]:
reg.fit(X_train, y_train)

LinearRegression()

In [90]:
reg.score(X_test, y_test)

0.905911242442266

In [92]:
reg.score(X_train, y_train)

0.8973793060969246

# Least Squared Linear Regression

# Regression Problem

In [98]:
from sklearn.neighbors import KNeighborsRegressor

In [101]:
knn = KNeighborsRegressor(n_neighbors=2)

In [103]:
knn.fit(X_train, y_train)

KNeighborsRegressor(n_neighbors=2)

In [105]:
knn.score(X_test, y_test)

0.8482509525160766

In [109]:
df.head()

   Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

# Classification Problem

In [107]:
from sklearn.neighbors import KNeighborsClassifier

In [117]:
inp = df.drop('Gender', axis=1)

In [119]:
out = df['Gender']

In [125]:
X_train, X_test, y_train, y_test = tts(inp, out, test_size = 0.3)

In [127]:
classifier = KNeighborsClassifier()

In [129]:
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [131]:
classifier.score(X_test, y_test)

0.9076743280093494

In [153]:
classifier.predict([[76.76, 344.]])

array([1])