In [1]:
lst = [100, 300, 250, 450, 150, 250, 500]

In [4]:
lst

[100, 300, 250, 450, 150, 250, 500]

In [8]:
import pandas as pd
df = pd.DataFrame(lst, columns=['cost'])
df

   cost
0   100
1   300
2   250
3   450
4   150
5   250
6   500

# Techniques to perform Feature Transformation:

1. Normalization <br>
2. Standardization <br>
3. Log Transformation <br>
4. Robust Scaler <br>
5. Max Absolute Scaler

# Normalization / min max scaler

In [17]:
min_cost = df.cost.min()
max_cost = df.cost.max()

In [19]:
min_cost

100

In [21]:
max_cost

500

In [23]:
df['cost_norm_manual'] = (df.cost - min_cost) / (max_cost - min_cost)

In [25]:
df

   cost  cost_norm_manual
0   100             0.000
1   300             0.500
2   250             0.375
3   450             0.875
4   150             0.125
5   250             0.375
6   500             1.000

<b>Using Sklearn Library

In [28]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
mms = MinMaxScaler()  # by default feature_range=(0, 1)

In [32]:
df['cost_norm_sklearn'] = mms.fit_transform(df[['cost']])

In [34]:
df

   cost  cost_norm_manual  cost_norm_sklearn
0   100             0.000              0.000
1   300             0.500              0.500
2   250             0.375              0.375
3   450             0.875              0.875
4   150             0.125              0.125
5   250             0.375              0.375
6   500             1.000              1.000

# Standardization / Standard Scaler

In [38]:
mean_cost = df.cost.mean()
std = df.cost.std()

In [40]:
std

146.38501094227996

In [42]:
df['cost_std_manual'] = (df.cost - mean_cost) / std

In [44]:
df

   cost  cost_norm_manual  cost_norm_sklearn  cost_std_manual
0   100             0.000              0.000        -1.268670
1   300             0.500              0.500         0.097590
2   250             0.375              0.375        -0.243975
3   450             0.875              0.875         1.122285
4   150             0.125              0.125        -0.927105
5   250             0.375              0.375        -0.243975
6   500             1.000              1.000         1.463850

In [46]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [50]:
df['cost_std_sklearn'] = scaler.fit_transform(df[['cost']])

In [52]:
df

,cost,cost_norm_manual,cost_norm_sklearn,cost_std_manual,cost_std_sklearn
0,100,0.000,0.000,-1.268670,-1.370320
1,300,0.500,0.500,0.097590,0.105409
2,250,0.375,0.375,-0.243975,-0.263523
3,450,0.875,0.875,1.122285,1.212206
4,150,0.125,0.125,-0.927105,-1.001388
5,250,0.375,0.375,-0.243975,-0.263523
6,500,1.000,1.000,1.463850,1.581139

In [70]:
std_ddof = df.cost.std(ddof=0)  ### Delta Degree of freedom (n-1)

In [56]:
std_ddof

135.52618543578768

In [58]:
std_ddof1 = df.cost.std(ddof = 1)

In [60]:
std_ddof1

146.38501094227996

In [62]:
df['cost_std_ddof0'] = (df.cost - mean_cost) / std_ddof

In [64]:
df

,cost,cost_norm_manual,cost_norm_sklearn,cost_std_manual,cost_std_sklearn,cost_std_ddof0
0,100,0.000,0.000,-1.268670,-1.370320,-1.370320
1,300,0.500,0.500,0.097590,0.105409,0.105409
2,250,0.375,0.375,-0.243975,-0.263523,-0.263523
3,450,0.875,0.875,1.122285,1.212206,1.212206
4,150,0.125,0.125,-0.927105,-1.001388,-1.001388
5,250,0.375,0.375,-0.243975,-0.263523,-0.263523
6,500,1.000,1.000,1.463850,1.581139,1.581139

In [66]:
df['cost_std_ddof1'] = (df.cost - mean_cost) / std_ddof1

In [68]:
df

,cost,cost_norm_manual,cost_norm_sklearn,cost_std_manual,cost_std_sklearn,cost_std_ddof0,cost_std_ddof1
0,100,0.000,0.000,-1.268670,-1.370320,-1.370320,-1.268670
1,300,0.500,0.500,0.097590,0.105409,0.105409,0.097590
2,250,0.375,0.375,-0.243975,-0.263523,-0.263523,-0.243975
3,450,0.875,0.875,1.122285,1.212206,1.212206,1.122285
4,150,0.125,0.125,-0.927105,-1.001388,-1.001388,-0.927105
5,250,0.375,0.375,-0.243975,-0.263523,-0.263523,-0.243975
6,500,1.000,1.000,1.463850,1.581139,1.581139,1.463850

# Log transformer

In [73]:
from sklearn.preprocessing import FunctionTransformer
import numpy as np

In [75]:
ft = FunctionTransformer(np.log1p)
df['cost_ft'] = ft.fit_transform(df[['cost']])
df

,cost,cost_norm_manual,cost_norm_sklearn,cost_std_manual,cost_std_sklearn,cost_std_ddof0,cost_std_ddof1,cost_ft
0,100,0.000,0.000,-1.268670,-1.370320,-1.370320,-1.268670,4.615121
1,300,0.500,0.500,0.097590,0.105409,0.105409,0.097590,5.707110
2,250,0.375,0.375,-0.243975,-0.263523,-0.263523,-0.243975,5.525453
3,450,0.875,0.875,1.122285,1.212206,1.212206,1.122285,6.111467
4,150,0.125,0.125,-0.927105,-1.001388,-1.001388,-0.927105,5.017280
5,250,0.375,0.375,-0.243975,-0.263523,-0.263523,-0.243975,5.525453
6,500,1.000,1.000,1.463850,1.581139,1.581139,1.463850,6.216606

# Robust Scaler

In [78]:
from sklearn.preprocessing import RobustScaler

In [80]:
rs = RobustScaler()
df['cost_robust_scaler'] = rs.fit_transform(df[['cost']])
df

,cost,cost_norm_manual,cost_norm_sklearn,cost_std_manual,cost_std_sklearn,cost_std_ddof0,cost_std_ddof1,cost_ft,cost_robust_scaler
0,100,0.000,0.000,-1.268670,-1.370320,-1.370320,-1.268670,4.615121,-0.857143
1,300,0.500,0.500,0.097590,0.105409,0.105409,0.097590,5.707110,0.285714
2,250,0.375,0.375,-0.243975,-0.263523,-0.263523,-0.243975,5.525453,0.000000
3,450,0.875,0.875,1.122285,1.212206,1.212206,1.122285,6.111467,1.142857
4,150,0.125,0.125,-0.927105,-1.001388,-1.001388,-0.927105,5.017280,-0.571429
5,250,0.375,0.375,-0.243975,-0.263523,-0.263523,-0.243975,5.525453,0.000000
6,500,1.000,1.000,1.463850,1.581139,1.581139,1.463850,6.216606,1.428571

# Max Abs Scaler

In [83]:
from sklearn.preprocessing import MaxAbsScaler

In [85]:
mas = MaxAbsScaler()

In [88]:
df['cost_max_abs'] = mas.fit_transform(df[['cost']])

In [90]:
df

,cost,cost_norm_manual,cost_norm_sklearn,cost_std_manual,cost_std_sklearn,cost_std_ddof0,cost_std_ddof1,cost_ft,cost_robust_scaler,cost_max_abs
0,100,0.000,0.000,-1.268670,-1.370320,-1.370320,-1.268670,4.615121,-0.857143,0.2
1,300,0.500,0.500,0.097590,0.105409,0.105409,0.097590,5.707110,0.285714,0.6
2,250,0.375,0.375,-0.243975,-0.263523,-0.263523,-0.243975,5.525453,0.000000,0.5
3,450,0.875,0.875,1.122285,1.212206,1.212206,1.122285,6.111467,1.142857,0.9
4,150,0.125,0.125,-0.927105,-1.001388,-1.001388,-0.927105,5.017280,-0.571429,0.3
5,250,0.375,0.375,-0.243975,-0.263523,-0.263523,-0.243975,5.525453,0.000000,0.5
6,500,1.000,1.000,1.463850,1.581139,1.581139,1.463850,6.216606,1.428571,1.0